server:
  port: 8081

logging:
  level:
    sql: info

spring:
  security:
    user:
      roles: SERVICE
      name: catalogue_service_user
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true